# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Just Write Mirror Images
email: jjustwrite@aol.com
description: > # this means to ignore newlines until "baseurl:"
  Just Write Mirror Images creates custom acrylic mirror party favors, sign-in boards, photo books, sign-in albums, centerpieces, keychains and many other products to enhance your special event.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.justwritemirrorimages.net/" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown

exclude: ['vendor']
